In [17]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
from statsmodels.tsa.stattools import grangercausalitytests

# 创建示例数据
np.random.seed(0)
data = pd.DataFrame(np.random.randn(100, 2), columns=['X', 'Y'])
data["Y"] = data["X"].shift(5).fillna(0)
# 假设X对Y有Granger因果关系
max_lag = 10  # 最大滞后阶数
test = 'ssr_chi2test'  # 使用卡方检验

# 进行Granger因果关系检验
results = grangercausalitytests(data[['Y', 'X']], max_lag, verbose=True)

# 打印检验结果
for lag in range(1, max_lag):
    p_value = results[lag][0][test][0]['ssr_chi2test'][1]
    print(f"Lag {lag}: p-value = {p_value}")

# 如果p-value小于显著性水平（例如0.05），可以拒绝零假设，表示存在Granger因果关系。


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.6876  , p=0.4090  , df_denom=96, df_num=1
ssr based chi2 test:   chi2=0.7091  , p=0.3997  , df=1
likelihood ratio test: chi2=0.7066  , p=0.4006  , df=1
parameter F test:         F=0.6876  , p=0.4090  , df_denom=96, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=1.0764  , p=0.3450  , df_denom=93, df_num=2
ssr based chi2 test:   chi2=2.2686  , p=0.3216  , df=2
likelihood ratio test: chi2=2.2428  , p=0.3258  , df=2
parameter F test:         F=1.0764  , p=0.3450  , df_denom=93, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.9150  , p=0.1328  , df_denom=90, df_num=3
ssr based chi2 test:   chi2=6.1920  , p=0.1026  , df=3
likelihood ratio test: chi2=6.0024  , p=0.1115  , df=3
parameter F test:         F=1.9150  , p=0.1328  , df_denom=90, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=4.5538  , p=0.0022  , df_d

InfeasibleTestError: The Granger causality test statistic cannot be compute because the VAR has a perfect fit of the data.

In [3]:
?grangercausalitytests

In [14]:
data[:10]

X         Y
0  1.764052  0.000000
1  0.978738  0.000000
2  1.867558  0.000000
3  0.950088  0.000000
4 -0.103219  0.000000
5  0.144044  1.764052
6  0.761038  0.978738
7  0.443863  1.867558
8  1.494079  0.950088
9  0.313068 -0.103219

In [8]:
range(1, 4)

range(1, 4)

In [18]:
results

{1: ({'ssr_ftest': (0.6876338377188705, 0.40902750631942153, 96.0, 1),
   'ssr_chi2test': (0.7091223951475852, 0.39973530945964175, 1),
   'lrtest': (0.7065947883348827, 0.40057658269564855, 1),
   'params_ftest': (0.6876338377188711, 0.40902750631942153, 96.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (1.0764439488181115, 0.345012897890353, 93.0, 2),
   'ssr_chi2test': (2.2686345587994605, 0.32164163776367644, 2),
   'lrtest': (2.2427742105611514, 0.3258275239430133, 2),
   'params_ftest': (1.0764439488181143, 0.34501289789035033, 93.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (1.915047465395498, 0.13278649184634383, 90.0, 3),
   'ssr_chi2test': (6.191986804778777, 0.10263422013819372, 3),
   'lrtest': (6.002381756019446, 0.11149440496890246, 3),
   'params_ftest': (1.9150474653954959, 0.13278649184634445, 90.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 

In [ ]:
sg_project2.csv